version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=V@|idPr0fil&$DBP@ssw0rd
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "V@|idPr0fil&$DBP@ssw0rd" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ValidProfiles;User Id=sa;Password=V@|idPr0fil&$DBP@ssw0rd;TrustServerCertificate=True
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  sqlserver_data: 